# Visualize costmap with cost overlay
python3 train_costmap_wf.py --exp-prefix test_ --batch-size 1 --test-batch-size 1 --worker-num 1 --test --test-traj --val-file arl_20220922_woods_hill_loop_low2.txt --stride 1 --skip 0 --crop-num 2 --data-root /project/learningphysics/arl_20220922_traj --load-model --model-name t_7_costnet_5000.pkl --network 2 --net-config 0 --out-vid-file arl_woods_hill_loop_low2.mp4
python3 train_costmap_wf.py --exp-prefix test_ --batch-size 1 --test-batch-size 1 --worker-num 1 --test --test-traj --val-file arl_20220922_woods_hill_loop_low2.txt --stride 1 --skip 0 --crop-num 2 --data-root /project/learningphysics/arl_20220922_traj --load-model --model-name t_8_costnet_5000.pkl --network 2 --net-config 0 --out-vid-file arl_woods_hill_loop_low2.mp4
python3 train_costmap_wf.py --exp-prefix test_ --batch-size 1 --test-batch-size 1 --worker-num 1 --test --test-traj --val-file arl_20220922_woods_hill_loop_low2.txt --stride 1 --skip 0 --crop-num 2 --data-root /project/learningphysics/arl_20220922_traj --load-model --model-name t_9_costnet_2500.pkl --network 2 --net-config 0 --out-vid-file arl_woods_hill_loop_low2.mp4
python3 train_costmap_wf.py --exp-prefix test_ --batch-size 1 --test-batch-size 1 --worker-num 1 --test --test-traj --val-file arl_20220922_woods_hill_loop_low2.txt --stride 1 --skip 0 --crop-num 2 --data-root /project/learningphysics/arl_20220922_traj --load-model --model-name t_10_costnet_2500.pkl --network 2 --net-config 0 --out-vid-file arl_woods_hill_loop_low2.mp4
python3 train_costmap_wf.py --exp-prefix test_ --batch-size 1 --test-batch-size 1 --worker-num 1 --test --test-traj --val-file arl_20220922_woods_hill_loop_low2.txt --stride 1 --skip 0 --crop-num 2 --data-root /project/learningphysics/arl_20220922_traj --load-model --model-name t_12_costnet_5000.pkl --network 2 --net-config 0 --out-vid-file arl_woods_hill_loop_low2.mp4

# Visualize aleatoric uncertainty (per model)
python3 train_costmap_wf_uncertainty.py --exp-prefix test_ --seed 1 --batch-size 1 --test-batch-size 1 --worker-num 1 --test --test-traj --val-file arl_20220922_woods_hill_loop_low2.txt --stride 1 --skip 0 --crop-num 2 --data-root /project/learningphysics/arl_20220922_traj --load-model --model-name a_1_costnet_5000.pkl --network 3 --net-config 0 --out-vid-file arl_woods_hill_loop_low2.mp4
python3 train_costmap_wf_uncertainty.py --exp-prefix test_ --seed 3 --batch-size 1 --test-batch-size 1 --worker-num 1 --test --test-traj --val-file arl_20220922_woods_hill_loop_low2.txt --stride 1 --skip 0 --crop-num 2 --data-root /project/learningphysics/arl_20220922_traj --load-model --model-name a_3_costnet_5000.pkl --network 3 --net-config 0 --out-vid-file arl_woods_hill_loop_low2.mp4
python3 train_costmap_wf_uncertainty.py --exp-prefix test_ --seed 15 --batch-size 1 --test-batch-size 1 --worker-num 1 --test --test-traj --val-file arl_20220922_woods_hill_loop_low2.txt --stride 1 --skip 0 --crop-num 2 --data-root /project/learningphysics/arl_20220922_traj --load-model --model-name a_15_costnet_5000.pkl --network 3 --net-config 0 --out-vid-file arl_woods_hill_loop_low2.mp4
python3 train_costmap_wf_uncertainty.py --exp-prefix test_ --seed 25 --batch-size 1 --test-batch-size 1 --worker-num 1 --test --test-traj --val-file arl_20220922_woods_hill_loop_low2.txt --stride 1 --skip 0 --crop-num 2 --data-root /project/learningphysics/arl_20220922_traj --load-model --model-name a_25_costnet_5000.pkl --network 3 --net-config 0 --out-vid-file arl_woods_hill_loop_low2.mp4
python3 train_costmap_wf_uncertainty.py --exp-prefix test_ --seed 30 --batch-size 1 --test-batch-size 1 --worker-num 1 --test --test-traj --val-file arl_20220922_woods_hill_loop_low2.txt --stride 1 --skip 0 --crop-num 2 --data-root /project/learningphysics/arl_20220922_traj --load-model --model-name a_30_costnet_5000.pkl --network 3 --net-config 0 --out-vid-file arl_woods_hill_loop_low2.mp4
python3 train_costmap_wf_uncertainty.py --exp-prefix test_ --seed 35 --batch-size 1 --test-batch-size 1 --worker-num 1 --test --test-traj --val-file arl_20220922_woods_hill_loop_low2.txt --stride 1 --skip 0 --crop-num 2 --data-root /project/learningphysics/arl_20220922_traj --load-model --model-name a_35_costnet_5000.pkl --network 3 --net-config 0 --out-vid-file arl_woods_hill_loop_low2.mp4

# Visualize epistemic uncertainty
# Network 2
python3 train_costmap_wf_uncertainty.py --exp-prefix en1_t1_ --batch-size 1 --test-batch-size 1 --worker-num 1 --test --test-traj-ensemble --val-file arl_20220922_woods_hill_loop_low2.txt --stride 1 --skip 0 --crop-num 2 --data-root /project/learningphysics/arl_20220922_traj --ensemble --ensemble-length 5 --load-model --ensemble-model-names t_7_costnet_5000.pkl t_8_costnet_5000.pkl t_9_costnet_2500.pkl t_10_costnet_2500.pkl t_12_costnet_5000.pkl --network 2 --net-config 0 --out-vid-file en1_t1_uncertainty.mp4
# Network 3
# OOD
python3 train_costmap_wf_uncertainty.py --exp-prefix en1_a1_ --batch-size 1 --test-batch-size 1 --worker-num 1 --test --test-traj-ensemble --val-file arl_20220922_woods_hill_loop_low2.txt --stride 1 --skip 0 --crop-num 2 --data-root /project/learningphysics/arl_20220922_traj --ensemble --ensemble-length 3 --load-model --ensemble-model-names a_1_costnet_5000.pkl a_3_costnet_5000.pkl a_15_costnet_5000.pkl --network 3 --net-config 0 --out-vid-file en1_a1_uncertainty.mp4
python3 train_costmap_wf_uncertainty.py --exp-prefix en2_ --batch-size 1 --test-batch-size 1 --worker-num 1 --test --test-traj-ensemble --val-file arl_20220922_woods_hill_loop_low2.txt --stride 1 --skip 0 --crop-num 2 --data-root /project/learningphysics/arl_20220922_traj --ensemble --ensemble-length 5 --load-model --ensemble-model-names a_1_costnet_5000.pkl a_3_costnet_5000.pkl a_25_costnet_5000.pkl a_30_costnet_5000.pkl a_35_costnet_5000.pkl --network 3 --net-config 0 --out-vid-file en2_uncertainty.mp4
# In Distribution
python3 train_costmap_wf_uncertainty.py --exp-prefix en1_control_ --batch-size 1 --test-batch-size 1 --worker-num 1 --test --test-traj-ensemble --val-file control_train_crop10.txt --stride 1 --skip 0 --crop-num 2 --data-root /project/learningphysics --ensemble --ensemble-length 3 --load-model --ensemble-model-names a_1_costnet_5000.pkl a_3_costnet_5000.pkl a_15_costnet_5000.pkl --network 3 --net-config 0 --out-vid-file en1_control_uncertainty.mp4
python3 train_costmap_wf_uncertainty.py --exp-prefix en2_control2_ --batch-size 1 --test-batch-size 1 --worker-num 1 --test --test-traj-ensemble --val-file control_train_crop10.txt --stride 1 --skip 0 --crop-num 2 --data-root /project/learningphysics --ensemble --ensemble-length 5 --load-model --ensemble-model-names a_1_costnet_5000.pkl a_3_costnet_5000.pkl a_25_costnet_5000.pkl a_30_costnet_5000.pkl a_35_costnet_5000.pkl --network 3 --net-config 0 --out-vid-file en2_control2_uncertainty.mp4

# Visualize total uncertainty
python3 train_costmap_wf_uncertainty.py --exp-prefix en1_total1_ --batch-size 1 --test-batch-size 1 --worker-num 1 --test --test-traj-ensemble --total-uncertainty --val-file arl_20220922_woods_hill_loop_low2.txt --stride 1 --skip 0 --crop-num 2 --data-root /project/learningphysics/arl_20220922_traj --ensemble --ensemble-length 5 --load-model --ensemble-model-names a_1_costnet_5000.pkl a_3_costnet_5000.pkl a_25_costnet_5000.pkl a_30_costnet_5000.pkl a_35_costnet_5000.pkl --network 3 --net-config 0 --out-vid-file en1_a1_uncertainty.mp4
